"""
Reads a version string from stdin and writes a python script which exports it
to stdout.
"""

import sys


def main():
    version = sys.stdin.read()
    version = version.strip()

    output = f"""\"\"\"
Generated by `scripts/wrap_version.py`.  Do not edit directly.
\"\"\"

VERSION = {version!r}
"""

    sys.stdout.write(output)


if __name__ == "__main__":
    main()
